version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: newproject
    container_name: newproject-application
    restart: unless-stopped
    volumes:
      - ./:/var/www:delegated

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    image: newproject-nginx
    container_name: newproject-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:delegated
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/:delegated,ro
    depends_on:
      - app
