version: '3'
services:
    app:
        build: 
            context: .
            dockerfile: .docker/php/Dockerfile
        image: newproject
        container_name: newproject-application
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    nginx:
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        image: newproject-nginx
        container_name: newproject-webserver
        restart: unless-stopped
        ports:
        - "8080:80"
        volumes:
        - ./:/var/www
        - .docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
        - app
    